global:
  scrape_interval: 60s
  evaluation_interval: 60s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: alertmanager
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']

  - job_name: cozify
    static_configs:
      - targets: ['cozify-exporter:5000']

  - job_name: ruuvi
    static_configs:
      - targets: ['172.22.0.1:9521']
    metric_relabel_configs:
      - source_labels: [device]
        regex: '^e1:70:26:63:b6:a2$'
        replacement: 'Terassi'
        target_label: name

      - source_labels: [device]
        regex: '^cb:e9:eb:0c:2f:2d$'
        replacement: 'MH yöpöytä'
        target_label: name

      - source_labels: [device]
        regex: '^fe:93:1c:0a:64:f0$'
        replacement: 'OH työpiste'
        target_label: name

      - source_labels: [device]
        regex: '^fa:6a:3b:33:47:2c$'
        replacement: 'Etuovi'
        target_label: name

remote_write:
  - url: "http://timescale-prometheus:9201/write"
remote_read:
  - url: "http://timescale-prometheus:9201/read"
